name: movies_web_scraper
description: Photo recommendations from Unsplash, web scraper.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.1.0
  flutter_dotenv: ^5.0.2
  envied: ^0.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true
